# 自动检查更新
# 默认值: true
check-update: true
# 是否启用基岩版玩家TPA菜单(/tpagui /tpaheregui)
# 默认值: true
bedrock-player-teleport-menu: true
# 是否启用基岩版玩家MSG菜单(/msggui)
# 默认值: true
bedrock-player-msg-menu: true
# 基础插件(可选值: auto/cmi/essentialsx/huskhomes/disable)
# 当选择auto时按照优先级自动修改为(cmi/essentialsx/huskhomes)其中之一
# 不需要此请设置为disable
# 不区分大小写 请注意有没有写漏字母!
# 默认值: auto
basic-plugin: "auto"
# 登录系统支持
login:
  # 是否启用基岩版玩家进服自动登录
  # 请注意，注册仍需玩家手动注册，后续登录才可以自动登录
  # 默认值: false
  enable: false
  # 使用的登录插件 (可选值: auto/authme/catseedlogin/nexauth/other)
  # 如果是AuthMe请填写authme 其他则为other
  # 当选择auto时如果服务器有安装AuthMe插件则自动更改为authme 否则自动关闭该功能
  # 如果不需要此功能 请将上方的enable设置为false
  # 不区分大小写 请注意有没有写漏字母!
  # 默认值: auto
  plugin: "auto"
  # 当plugin设置为other时 将会调用这里设置的命令在控制台为基岩版玩家自动登录
  # 如果你的登录插件没有强制登录命令 请关闭此功能
  # 可用变量: %player%: 玩家名
  # 默认值: "forcelogin %player%"
  forcelogin-command: "forcelogin %player%"
  # 自动登录时发送给基岩版玩家的信息
  # 默认值: "&a检测到你是基岩版玩家，已自动登录!"
  auto-message: "&a检测到你是基岩版玩家，已自动登录!"

# 配置文件版本 (请不要自己修改该值!!!)
config-version: ${project.version}
