# 检查更新
check-update: true
# 登录系统支持
login:
  # 是否启用登录系统支持
  enable: false
  # 支持模式
  # 设置为0时，基岩版玩家进服会弹出GUI让玩家输入密码
  # 设置为1时，基岩版玩家进服自动登录
  mode: 0
  # 自动登录时发送给基岩版玩家的信息
  auto-message: "&a检测到你是基岩版玩家，已自动登录!"
  # 玩家关闭登录GUI时踢出的提示
  kick-message: "&4你关闭了登录GUI，已被系统踢出!"