name: BedrockPlayerSupport
version: '${project.version}'
main: cn.dsnbo.bedrockplayersupport.BedrockPlayerSupport
api-version: 1.13
folia-supported: true
depend:
  - floodgate
softdepend:
  - CMI
  - Essentials
  - HuskHomes
  - AuthMe
  - CatSeedLogin
  - NexAuth
authors: [ DongShaoNB ]
description: Make it easier for bedrock player to use plugins
website: www.dsnbo.cn

commands:
  tpgui:
    description: "Bedrock player teleport form"
  msggui:
    description: "Bedrock player msg form"
